"use client";
import { useEffect, useState } from "react";
import { AudioPlayer } from "./AudioPlayer";
import { ANSWER_LABEL, type Answer, type Question } from "@/lib/types";
import { APP } from "@/lib/config";
type Stats = { score: number; correct: number; wrong: number; unknown: number };
export function QuizClient({ category }: { category: string }) {
  const [items, setItems] = useState<Question[]>([]); const [index, setIndex] = useState(0); const [played, setPlayed] = useState(false); const [feedback, setFeedback] = useState<Answer | null>(null); const [stats, setStats] = useState<Stats>({ score: 0, correct: 0, wrong: 0, unknown: 0 }); const [error, setError] = useState("");
  useEffect(() => { fetch(`/api/questions${category !== "综合" ? `?category=${encodeURIComponent(category)}` : ""}`).then(r => r.ok ? r.json() : Promise.reject()).then((x: Question[]) => { if (!x.length) setError("这个题库还没有题目，请先到后台添加。 "); else setItems(x.sort(() => Math.random() - .5)); }).catch(() => setError("无法连接题库。请检查 Supabase 配置。")); }, [category]);
  const answer = (choice: Answer) => { if (!items[index] || feedback || (!played && APP.requireAudioPlayed)) return; const q = items[index]; const right = choice === q.correct_answer; const update = choice === "unknown" ? { score: stats.score - 1, correct: stats.correct, wrong: stats.wrong, unknown: stats.unknown + 1 } : right ? { score: stats.score + q.score, correct: stats.correct + 1, wrong: stats.wrong, unknown: stats.unknown } : { score: stats.score + q.penalty, correct: stats.correct, wrong: stats.wrong + 1, unknown: stats.unknown };
    setStats(update); setFeedback(choice); setTimeout(async () => { if (index + 1 >= items.length) { const data = { total_score:update.score, correct_count:update.correct, wrong_count:update.wrong, unknown_count:update.unknown, accuracy: Math.round(update.correct / items.length * 100), category }; try { const response = await fetch("/api/records", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(data) }); const saved = await response.json(); sessionStorage.setItem("vaq-result", JSON.stringify({ ...data, recordId:saved.id })); } catch { sessionStorage.setItem("vaq-result", JSON.stringify(data)); } location.href = "/result"; } else { setIndex(v=>v+1); setPlayed(false); setFeedback(null); } }, 650); };
  if (error) return <main className="grid min-h-screen place-items-center p-6"><div className="glass max-w-md rounded-3xl p-8 text-center">{error}<a className="mt-5 block text-cyan underline" href="/">返回首页</a></div></main>;
  if (!items.length) return <main className="grid min-h-screen place-items-center text-cyan">正在接入题库…</main>;
  const q = items[index]; return <main className="mx-auto min-h-screen max-w-xl px-5 py-7"><div className="enter"><div className="mb-7 flex justify-between text-sm text-slate-400"><span>第 {index + 1} / {items.length} 题</span><span>{category}</span></div><div className="mb-8 h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-cyan transition-all duration-500" style={{ width: `${(index + 1) / items.length * 100}%` }} /></div><section className="glass rounded-[2rem] p-6 sm:p-8"><p className="mb-3 text-xs tracking-[.24em] text-cyan">LISTEN CAREFULLY</p><h1 className="mb-7 text-2xl font-bold leading-relaxed">{q.title}</h1><AudioPlayer key={q.id} src={q.audio_url} onUnlocked={() => setPlayed(true)} /><p className="my-6 text-center text-xs text-slate-400">{!played && APP.requireAudioPlayed ? "请先播放音频后作答" : "这段声音，属于她吗？"}</p><div className="grid gap-3">{(["yes", "no", "unknown"] as Answer[]).map(a => <button key={a} disabled={Boolean(feedback) || (!played && APP.requireAudioPlayed)} onClick={() => answer(a)} className={`rounded-2xl border border-white/10 bg-white/5 px-5 py-4 text-left text-lg transition hover:border-cyan/60 hover:bg-cyan/10 active:scale-[.98] disabled:opacity-40 ${feedback === a ? (a === "unknown" ? "unknown" : a === q.correct_answer ? "correct" : "wrong") : ""}`}><span className="mr-3 text-cyan">{a === "yes" ? "01" : a === "no" ? "02" : "03"}</span>{ANSWER_LABEL[a]}</button>)}</div></section></div></main>;
}
